config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"posts#index"
  resources :posts, except: :index

  resources :regisrations, only: [:create] do
    collection do
      get "signup"
      post "signup_validates"
      get "signup_2"
    end
  end
  resources :users, only: [:show]
  resources :categories, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/month.rb
class Month < ActiveHash::Base
  self.data = [
      {id: 1, name: "1月"}, {id: 2, name: "2月"}, {id: 3, name: "3月"},
      {id: 4, name: "4月"}, {id: 5, name: "5月"}, {id: 6, name: "6月"},
      {id: 7, name: "7月"}, {id: 8, name: "8月"}, {id: 9, name: "9月"},
      {id: 10, name: "10月"}, {id: 11, name: "11月"}, {id: 12, name: "12月"},
  ]
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user

  validates :title, presence: true
  validates :category, presence: true
  validates :content, presence: true

  enum category: { "生活、暮らし": 1,
                   "仕事": 2,
                   "趣味": 3,
                   "プログラミング": 4,
                   "その他": 5}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  extend ActiveHash::Associations::ActiveRecordExtensions

  has_many :posts
  belongs_to_active_hash :year
  belongs_to_active_hash :month

  enum date: {"1日": 1,"2日": 2, "3日": 3, "4日": 4, "5日": 5, "6日": 6, "7日": 7, "8日": 8, "9日": 9, "10日": 10,
              "11日": 11,"12日": 12, "13日": 13, "14日": 14, "15日": 15, "16日": 16, "17日": 17, "18日": 18, "19日": 19, "20日": 20,
              "21日": 21,"22日": 22, "23日": 23, "24日": 24, "25日": 25, "26日": 26, "27日": 27, "28日": 28, "29日": 29, "30日": 10,
              "31日": 31}


  validates :nickname, presence: true, uniqueness: true, length: { maximum: 6 }
  validates :email, presence: true, uniqueness: true
  validates :phone_number, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :year_id, presence: {message:"を選択して下さい"}
  validates :month_id, presence: {message:"を選択して下さい"}
  validates :date_id, presence: {message:"を選択して下さい"}
end

app/models/year.rb
class Year < ActiveHash::Base
  self.data = [ {id:1, name: "1970年"}, {id:2, name: "1971年"}, {id:3, name: "1972年"},
                {id:4, name: "1973年"}, {id:5, name: "1974年"}, {id:6, name: "1975年"},
                {id:7, name: "1976年"}, {id:8, name: "1977年"}, {id:9, name: "1978年"},
                {id:10,name: "1979年"}, {id:11,name: "1980年"}, {id:12,name: "1981年"},
                {id:13,name: "1982年"}, {id:14,name: "1983年"}, {id:15,name: "1984年"},
                {id:16,name: "1985年"}, {id:17,name: "1986年"}, {id:18,name: "1987年"},
                {id:19,name: "1988年"}, {id:20,name: "1989年"}, {id:21,name: "1990年"},
                {id:22,name: "1991年"}, {id:23,name: "1992年"}, {id:24,name: "1993年"},
                {id:25,name: "1994年"}, {id:26,name: "1995年"}, {id:27, name:"1996年"},
                {id:28,name: "1997年"}, {id:29, name:"1998年"}, {id:30, name:"1999年"},
                {id:31,name: "2000年"}, {id:32,name: "2001年"}, {id:33,name: "2002年"},
                {id:34,name: "2003年"}, {id:35,name: "2004年"}, {id:36,name: "2005年"},
                {id:37,name: "2006年"}, {id:38,name: "2007年"}, {id:39, name:"2008年"},
                {id:40,name: "2009年"}, {id:41,name: "2010年"}, {id:42,name: "2011年"},
                {id:43,name: "2012年"}, {id:44,name: "2013年"}, {id:45,name: "2014年"},
                {id:46,name: "2015年"}, {id:47,name: "2016年"}, {id:48,name: "2017年"},
                {id:49,name: "2018年"}, {id:50,name: "2019年"}
              ]
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_parmitted_parameters, if: :devise_controller?

  protected

  def configure_parmitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:
    [:nickname, :last_name, :first_name,:last_name_k, :first_name_k,
     :year, :month, :date, :phone_number, :icon])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit]
  before_action :authenticate_user!, expect: [:index]

  def index
    @posts = Post.includes(:user)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to root_path
    else
      render action: :new
    end
  end

  def show
    
  end

  def edit

  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end
  
  private

  def post_params
    params.require(:post).permit(:title, :category, :image, :content).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/controllers/regisrations_controller.rb
class RegisrationsController < ApplicationController

  def signup
    @user = User.new
  end

  def signup_validates
    session[:icon] = user_params[:icon]
    session[:nickname] = user_params[:nickname]
    session[:email] = user_params[:email]
    session[:password] = user_params[:password]

    @user = User.new(
      icon: session[:icon],
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password]
    )
    
    @user.valid?

    skip_validate(@user.errors)

    if @user.errors.messages.blank? && @user.errors.details.blank?
      redirect_to signup_2_regisrations_path
    else
      render :signup
    end

  end


  def signup_2
    @user = User.new
  end

  def create
    @user = User.new(
      icon: session[:icon],
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      last_name: user_params[:last_name],
      first_name: user_params[:first_name],
      year_id: user_params[:year_id],
      month_id: user_params[:month_id],
      date_id: user_params[:date_id],
      phone_number: user_params[:phone_number]
    )

    if @user.errors.messages.blank? && @user.errors.details.blank?
      if @user.save
        sign_in User.find(@user.id) unless user_signed_in?
        session.delete(:icon)
        session.delete(:nickname)
        session.delete(:email)
        session.delete(:password)
        session.delete(:last_name)
        session.delete(:first_name)
        session.delete(:year_id)
        session.delete(:month_id)
        session.delete(:date_id)
        session.delete(:phone_number)
        redirect_to root_path
      else
        render :signup_2
      end
    else
      render :signup_2
    end
  end



  private

  def user_params
    params.require(:user).permit(:icon, :nickname,:email, :password, :last_name, :first_name,
                                 :year_id, :month_id, :date_id, :phone_number)
  end

  def skip_validate(errors)
    errors.messages.delete(:last_name)
    errors.details.delete(:last_name)
    errors.messages.delete(:first_name)
    errors.details.delete(:first_name)
    errors.messages.delete(:year_id)
    errors.details.delete(:year_id)
    errors.messages.delete(:month_id)
    errors.details.delete(:month_id)
    errors.messages.delete(:date_id)
    errors.details.delete(:date_id)
    errors.messages.delete(:phone_number)
    errors.details.delete(:phone_number)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/regsrations_helper.rb
module RegsrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MyBlog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    "https://fonts.googleapis.com/css?family=Londrina+Shadow"

  %body
    .header
      .header__title
        = link_to root_path, class:"header__title__top" do
          MyBlog
      .header__right
        - if user_signed_in?
          = link_to user_path(current_user), class:"header__right__btn" do
            = current_user.nickname
          = link_to new_post_path, class:"header__right__btn" do
            投稿する
          = link_to destroy_user_session_path, method: :delete, class:"header__right__btn" do
            ログアウト
        - else
          = link_to new_user_session_path, class:"header__right__btn" do
            ログイン
          = link_to signup_regisrations_path, class:"header__right__btn" do
            新規登録
    = yield

app/views/posts/_contents.html.haml
.content
  .content__left
    .content__left__image
      = image_tag post.image.url
  .content__right
    .content__right__title
    = link_to post_path(post.id) do
      = post.title
    .content__right__created
      = post.created_at

app/views/posts/_posts.html.haml
.content
  .content__left
    .content__left__image
      - if post.image?
        = image_tag post.image.url, size:"200x200", id:"circle__pic"
      - else
        = image_tag "no-image.png"
  .content__right
    .content__right__title
    = link_to post_path(post.id), id:"content__title" do
      = post.title
    .content__bottom
      .content__bottom__name
        = link_to user_path(post.user), id:"content__name" do
          = post.user.nickname
      .content__bottom__created
        = post.created_at

app/views/posts/edit.html.haml
.contents
  .post__title
    編集
  
  = form_with model:@post, class:"form", local: true do |f|
    = f.text_field :title, placeholder:"TITLE", class:"form__title"
    = f.select :category, Post.categories.keys, {prompt: "Select a Category"}, {class:"form__category"}
    = f.label :image, id: "image__label" do
      %i.far.fa-image
      = f.file_field :image, class:"form__image"
    = f.text_area :content, placeholder:"CONTENT", class:"form__content"
    = f.submit "投稿", class:"form__btn"

app/views/posts/index.html.haml
.contents
  .contents__title
    ブログ一覧
  - @posts.each do |post|
    = render "posts", post: post

app/views/posts/new.html.haml
.contents
  .post__title
    投稿する
  
  = form_with model:@post, class:"form", local: true do |f|
    = f.text_field :title, placeholder:"タイトル", class:"form__title"
    -if @post.errors.any?
      %ul
        %li.formError= @post.errors.full_messages_for(:title).first
        
    = f.select :category, Post.categories.keys, {prompt: "カテゴリーを選択してください"}, {class:"form__category"}

    = f.label :image, id: "image__label" do
      %i.far.fa-image
      = f.file_field :image, class:"form__image"
    -if @post.errors.any?
      %ul
        %li.formError= @post.errors.full_messages_for(:category).first

    = f.text_area :content, placeholder:"本文", class:"form__content"
    -if @post.errors.any?
      %ul
        %li.formError= @post.errors.full_messages_for(:content).first
        
    = f.submit "投稿する", class:"form__btn"

app/views/posts/show.html.haml
.contents
  .post__title
    = @post.title
  .post__category
    カテゴリー :
    = @post.category
  .post__created_at
    = @post.created_at
  .post__manage
    - if user_signed_in? && current_user.id == @post.user_id
      = link_to edit_post_path(@post.id), class:"post__manage__edit" do
        編集
      = link_to post_path(@post.id), method: :delete, class:"post__manage__delete" do
        削除
  .post__image
    - if @post.image?
      = image_tag @post.image.url, size:"400x400", class:"post__image__pic"
    - else
      %div
  .post__content
    = simple_format @post.content
  

app/views/regisrations/signup.html.haml
.contents
  .contents__title ユーザー新規登録
  = form_with model:@user, url:signup_validates_regisrations_path, local: true do |f|
    = f.label :icon, id:"icon__label" do
      %i.far.fa-smile
        .icon__text
          タップしてアイコンを選択
      = f.file_field :icon, class:"icon__field"
    .fields
      .field__nickname
        ニックネーム
        %span#field__require
          必須
      = f.label :nickname, class:"field__label" do
        %i.fas.fa-signature
        = f.text_field :nickname, autofocus: true, placeholder:"例）ブログ太郎",class:"field__input"
      - if @user.errors.any?
        %ul
          %li.formError= @user.errors.full_messages_for(:nickname).first

      .field__email
        メールアドレス
        %span#field__require
          必須
      = f.label :email, class:"field__label" do
        %i.far.fa-envelope
        = f.email_field :email, autofocus: true, autocomplete: "email", placeholder:"PC、携帯どちらでも可", class:"field__input"
      - if @user.errors.any?
        %ul
          %li.formError= @user.errors.full_messages_for(:email).first
      .field__password
        パスワード
        %span#field__require
          必須
      = f.label :password, class:"field__label" do
        %i.fas.fa-key
        = f.password_field :password, autocomplete: "new-password", placeholder:"６文字以上の英数字",class:"field__input" 
      - if @user.errors.any?
        %ul
          %li.formError= @user.errors.full_messages_for(:password).first
      .actions
        = f.submit "次へ"

app/views/regisrations/signup_2.html.haml
.contents
  = form_with model:@user, url:regisrations_path, method: :post, local: true do |f|
    .fields
      .fields__title
        個人情報入力
      .field__name
        名前（全角)
        %span#field__require
          必須
      .field__name__last
        = f.label :last_name, class:"label__fname" do
          %i.fas.fa-signature.sign
          = f.text_field :last_name, autofocus: true, placeholder:"例）山田",class:"field__lname"
        - if @user.errors.any?
          %ul
            %li.formError= @user.errors.full_messages_for(:last_name).first
      .field__name__first
        = f.label :first_name, class:"label__fname" do
          %i.fas.fa-signature.sign
          = f.text_field :first_name, autofocus: true, placeholder:"例）太郎", class:"field__fname"
        - if @user.errors.any?
          %ul
            %li.formError= @user.errors.full_messages_for(:first_name).first
      .field__birth
        生年月日
        %span#field__require
          必須
      .field__birth__year
        = f.label :year_id, class:"label__year" do
          %i.fas.fa-angle-down
          = f.collection_select :year_id, Year.all, :id, :name, {prompt: "年"}, {class:"field__year"}
      - if @user.errors.any?
        %ul
          %li.formError= @user.errors.full_messages_for(:year_id).first
      .field__birth__month
        = f.label :month_id, class:"label__month" do
          %i.fas.fa-angle-down
          = f.collection_select :month_id, Month.all, :id, :name, {prompt:"月"}, {class:"field__month"}
      - if @user.errors.any?
        %ul
          %li.formError= @user.errors.full_messages_for(:month_id).first
      .field__birth__date
        = f.label :date_id, class:"label__date" do
          %i.fas.fa-angle-down
          = f.select :date_id, User.dates.keys, {prompt:"日"}, {class:"field__date"}
      - if @user.errors.any?
        %ul
          %li.formError= @user.errors.full_messages_for(:date_id).first
      .field__number
        電話番号
        %span#field__require2
          任意
        .field__number__phone
          = f.label :phone_number, class:"label__phone" do
            %i.fas.fa-phone
            = f.text_field :phone_number, placeholder:"例）09000000000", class:"field__phone"
      .actions
        = f.submit "登録する"

app/views/users/show.html.haml
.contents
  .contents__user
    = @user.nickname
    のブログ
  - @posts.each do |post|
    = render "posts/posts", post: post